### ISSUE TITLE
Minor Typo on ToDoList - Part one

### ISSUE THREAD

**Issue by dougferg** [Zaid-Ajaj/the-elmish-book#101]
The work "the" is duplicated on this page: <https://zaid-ajaj.github.io/the-elmish-book/#/chapters/elm/todo-app-part1>

--typing in the text box and clicking the the Add button--

**Comment by Zaid-Ajaj** [comment]
Hi @dougferg I totally missed this issue! Thanks a lot for letting me know about the typo, it should be now be fixed
