### ISSUE TITLE
Typos on RecursiveUpdates page

### ISSUE THREAD

**Issue by dougferg** [Zaid-Ajaj/the-elmish-book#116]
https://zaid-ajaj.github.io/the-elmish-book/#/chapters/commands/recursive-updates

1. The word "of" is repeated here: "you factor out the branch of of the"
2. Looks like an editing issue: "Then use this function the branch of SetInputDate:"

**Comment by Zaid-Ajaj** [comment]
Thanks for filing the issue @dougferg! You can always send PRs with the desired fix and it will be automatically updated on the website. I could do it too but it might take a while, I appreciate all the help from the community :smile:
