### ISSUE TITLE
Suggestion on Modelling Async State Page

### ISSUE THREAD

**Issue by dougferg** [Zaid-Ajaj/the-elmish-book#117]
This is very minor, but you might want to change the order of your operations in the F# code to match the text written below it.  

The f# code is 
type Msg =
  // messages for Operation 1 -> might fail
  | StartOperationOne
  | FinishOperationOneSuccessfully of ResultOfOne
  | FinishOperationOneWithError of exn
  // messages for Operation 2 -> always succeeds
  | StartOperationTwo
  | FinishOperationTwo of ResultOfTwo

and the text below says: 
(1) Operations that always succeed (for example, a delay)
(2) Operations that fail

It might be better to change the Messages to reflect the order in which you discuss them in the text.
type Msg =
  // messages for Operation 1 -> might fail
  | StartOperationOne
  | FinishOperationOne of ResultOfOne`
  // messages for Operation 1 -> always succeeds
  | StartOperationTwo
  | FinishOperationTwoSuccessfully of ResultOfTwo
  | FinishOperationTwoWithError of exn

**Comment by Zaid-Ajaj** [comment]
Hello there @dougferg, this would definitely be a nice improvement! Would you like to send a PR with the fix? I would really appreciate your help 🙏 :smile:

**Comment by dougferg** [comment]
I would be happy to do that.  
I'll submit a separate PR to fix the typos I found as well.
Thanks so much for the book @Zaid-Ajaj.

**Comment by Zaid-Ajaj** [comment]
That is awesome :100: :fire: thanks a lot!
