### ISSUE TITLE
Missing prop.className overload: (bool * string) list

### ISSUE THREAD

**Issue by eferfolja** [Zaid-Ajaj/the-elmish-book#127]
According to the page Using CSS, section Conditional classes, there is supposed to be an overload for _prop.className_ with an input parameter of type: **_(bool * string) list_**.

I checked Feliz/Properties.fs, there is no such overload.

**Comment by Zaid-Ajaj** [comment]
Hi @eferfolja, as of Feliz v1.0 this overload no longer exists I will need to update some parts of the book accordingly. Thanks for pointing it out, I will keep it mind for when time permits to actually update the book to match the current state state of things :smile:
