### ISSUE TITLE
Links to exercise solution are dead

### ISSUE THREAD

**Issue by OmanF** [Zaid-Ajaj/the-elmish-book#129]
The link to the solution of the todo app is broken, leading to `404`.
I assume but have not verified, the other exercise link is also dead.

Maybe because it leads to `...github.io/...`? I don't know, only guessing.

**Comment by Zaid-Ajaj** [comment]
Hi there @OmanF, which links exactly are dead and on which page? I will check them out

**Comment by OmanF** [comment]
Hi.
At the end of both exercises 1 and 3 there's a link with the text `You can view and use the application *live here*`. Both lead to the same URL: `https://zaid-ajaj.github.io/elmish-todo-exercises/` which gives 404.

**Comment by Zaid-Ajaj** [comment]
I see, thanks a lot @OmanF I will make sure to get them back online asap

**Comment by OmanF** [comment]
Thanks for bringing the demo up again. It's a good reference.
Closing.

**Comment by OmanF** [comment]
BTW, any chance you could also post the code?

For example, I, personally, am having an issue with persisting the lists. I tried going at with several different approaches but they all fail.
It would help greatly to see the "official" solution.

Thanks, either way, *love* your work!
