### ISSUE TITLE
Running `npm run build` for Hello-World Requires Webpack to Be Installed

### ISSUE THREAD

**Issue by morgankenyon** [Zaid-Ajaj/the-elmish-book#136]
_tldr;_

More of an FYI for someone who is working the the first example, I got some webpack errors which I was able to resolve. It might be worth adding an FYI box to let people know they might need to separately install webpack to get the first example working. Especially if they're new to node/F# it might throw them for a loop.

To get working I ran:

`npm install -g webpack` and `npm install -g webpack-cli`.

_Full repo_

I was working my way through your [Fable Hello-World ](https://zaid-ajaj.github.io/the-elmish-book/#/chapters/fable/hello-world) example. I cloned the repo, ran npm install, then when I ran `npm run build` I got the following error:

```
C:\dev\elmish_book\fable-getting-started [master ≡ +1 ~0 -0 !]> npm run build

> webpack

'webpack' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build: `webpack`
npm ERR! Exit status 1
npm ERR! Failed at the @ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\morga\AppData\Roaming\npm-cache\_logs\2020-06-13T02_09_59_881Z-debug.log
```

Which I ran `npm install -g webpack` to install then, then ran into an issue with webpack cli:

```
C:\dev\elmish_book\fable-getting-started [master ≡ +1 ~0 -0 !]> npm run build

> @ build C:\dev\elmish_book\fable-getting-started
> webpack

One CLI for webpack must be installed. These are recommended choices, delivered as separate packages:
 - webpack-cli (https://github.com/webpack/webpack-cli)
   The original webpack full-featured CLI.
We will use "npm" to install the CLI via "npm install -D".
Do you want to install 'webpack-cli' (yes/no): y
Installing 'webpack-cli' (running 'npm install -D webpack-cli')...
+ webpack-cli@3.3.11
updated 2 packages and audited 651 packages in 4.194s
found 16 vulnerabilities (15 low, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details
Error: Cannot find module 'webpack-cli'
Require stack:
- C:\Users\morga\AppData\Roaming\npm\node_modules\webpack\bin\webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at C:\Users\morga\AppData\Roaming\npm\node_modules\webpack\bin\webpack.js:143:5
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  requireStack: [
    'C:\\Users\\morga\\AppData\\Roaming\\npm\\node_modules\\webpack\\bin\\webpack.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! @ build: `webpack`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\morga\AppData\Roaming\npm-cache\_logs\2020-06-13T02_12_07_588Z-debug.log
```
And to fix that I ran `npm install -g webpack-cli`.

**Comment by Zaid-Ajaj** [comment]
Hi there @morgankenyon, 

Actually you shouldn't install webpack and webpack-cli as global tools on your machine. Instead, you install them locally via `npm install` first before you run `npm run build`

**Comment by morgankenyon** [comment]
I didn't mention it, but I did run `npm install` before running `npm run build` but still encountered the errors above. 

I had to run `npm install` a couple times because I ran into some issues with it. Now that you've mentioned not installing those globally, I've never had to install webpack separately on the other npm projects that I've used in the past. So it was a bit odd.

**Comment by Zaid-Ajaj** [comment]
Can you please give it another try from a clean clone? It might have been some weird admin privilege issue when you opened the repo from the terminal

**Comment by morgankenyon** [comment]
I retried it and no errors occurred as expected. Not sure what I ran into the first time, thanks for your assistance.

**Comment by Zaid-Ajaj** [comment]
Happy to hear it worked out for you :smile: thanks for the follow-up
