### ISSUE TITLE
Where does the state value come from?

### ISSUE THREAD

**Issue by bytesource** [Zaid-Ajaj/the-elmish-book#141]
Hi Zaid,

In the section [Modelling nested routes >> Passing URLs to child programs](https://zaid-ajaj.github.io/the-elmish-book/#/chapters/scaling/modelling-nested-routes#passing-urls-to-child-programs) there is a value `state` that I'm not sure where it came from: 

``` fsharp
// App.fs
let init() =
  let currentUrl = parseUrl(Router.currentUrl())
  match currentUrl with
  | Url.User userUrl ->
      let (userState, userCmd) = User.init userUrl
      { state with
          CurrentUrl = currentUrl
          CurrentPage = Page.User userState }, Cmd.map UserMsg userCmd
  // ...
```

Peeking at the next chapter I saw that you initialized a `defaultState` inside `init()`, is this what you are doing here?

**Comment by Zaid-Ajaj** [comment]
Should be fixed now, thanks for pointing it out and sorry it took so long!

There was no `defaultState`, here we are just constructing the state with only two fields: `CurrentUrl` and `CurrentPage`
