### ISSUE TITLE
For .NET 5 preview and F# 5 Async.Sleep now has an overload

### ISSUE THREAD

**Issue by voroninp** [Zaid-Ajaj/the-elmish-book#147]
So [Delayed Increments](https://zaid-ajaj.github.io/the-elmish-book/#/chapters/fable/counter#delayed-increments-and-decrements) section leads to the error:

> A unique overload for method 'Sleep' could not be determined based on type information prior to this program point. A type annotation may be needed.
>
>Known type of argument: 'a
>
>Candidates:
> - static member Async.Sleep : dueTime:System.TimeSpan -> Async<unit>
> - static member Async.Sleep : millisecondsDueTime:int -> Async<unit>

Now it should be `do! Async.Sleep (ms: int)` instead of `do! Async.Sleep ms` 
or 
`let runAfter (ms: int) callback =` instead of `let runAfter ms callback =`

**Comment by Zaid-Ajaj** [comment]
Great catch @voroninp! I haven't checked which parts are different in NET5 so this is good to know :smile: 

Would you be willing to make a small PR for this issue? 🙏 I would really appreciate it

**Comment by voroninp** [comment]
Yes, sure.
