### ISSUE TITLE
Update date-fns to 2.16.1

### ISSUE THREAD

**Issue by marlinla** [Zaid-Ajaj/the-elmish-book#158]
Update the npm install command to match latest version. Previous command will break Hackernews exercises. 

``npm install date-fns@1.30.1`` to ``npm install date-fns@2.16.1``

https://github.com/Zaid-Ajaj/Fable.DateFunctions
https://zaid-ajaj.github.io/the-elmish-book/#/chapters/commands/elmish-hackernews-exercises

**Comment by Zaid-Ajaj** [comment]
Done! thanks for pointing this out 😉
