### ISSUE TITLE
Dark color scheme contrast is too low

### ISSUE THREAD

**Issue by inputusernamehere** [Zaid-Ajaj/the-elmish-book#162]
I feel bad opening an issue for such a minor nitpick when your book is otherwise so good, but oh well. These seem to be the colors used for the scroll bar currently: https://www.colorcombos.com/combotester.html?color0=26282c&color1=1c1e21&color2=18191b

The contrast between these are too low, so it's almost impossible to find the scroll handle.

**Comment by Zaid-Ajaj** [comment]
Hi there @inputusernamehere thanks for filing the issue! there is always room for improvement. The styles of the scroll bars is defined in [this file](https://github.com/Zaid-Ajaj/the-elmish-book/blob/master/styles/website.css) if you know to detect dark color scheme and fix the contrast, would be really appreciated 🙏 (I don't know how to do that tbh)
