### ISSUE TITLE
Router.navigate vs. Cmd.navigate in "Programmatic Navigation" chapter?

### ISSUE THREAD

**Issue by WallaceKelly** [Zaid-Ajaj/the-elmish-book#173]
In [this code sample](https://github.com/Zaid-Ajaj/the-elmish-book/blob/8ff6ff2b011be7da31f6ef4e79ae5d0cbfcc8969/chapters/scaling/programmatic-navigation.md?plain=1#L22-L23) from The Elmish Book...

```fsharp {highlight: [4, 5]}
let update (msg: Msg) (state: State) =
  match msg with
  | UrlChanged url -> { state with CurrentUrl = url }, Cmd.none
  | NavigateToContact ->  state, Router.navigate("contact")
  | NavigateToAbout -> state, Router.navigate("about")
```

...using the `Router.navigate(...)` methods does not work for me. In contrast, using `Cmd.navigate(...)` does work. Do you think this is a bug in the sample? Or something different about my project?

![image](https://user-images.githubusercontent.com/698424/155445763-119acd1e-641b-4a22-aab4-b6789cdc68f9.png)

Here are my library references:

```
<PackageReference Include="Fable.Elmish.React" Version="3.0.1" />
<PackageReference Include="Fable.SimpleHttp" Version="3.0.0" />
<PackageReference Include="Feliz" Version="1.51.0" />
<PackageReference Include="Feliz.Bulma" Version="2.18.0" />
<PackageReference Include="Feliz.Router" Version="3.8.0" />
```

And my open directives:

```
open Elmish
open Feliz
open Feliz.Bulma
open Feliz.Router
```

I'd be glad to assemble a PR, if the code sample should be corrected.

**Comment by MangelMaxime** [comment]
Hello @WallaceKelly,

I don't know Feliz.Router well but looking at the error signature `Cmd.navigate` seems the right option here.

`Router.navigate` seems to return `unit` and not a `Cmd<'T>`.

I suppose `Router.navigate` can be used inside a callback or from the view.

**Comment by WallaceKelly** [comment]
Upon further investigation, I find that this change is a difference between Feliz.Router 2.x and Feliz.Router 3.x.

https://github.com/Zaid-Ajaj/Feliz.Router#migrating-from-2x-to-3x says,

> The 3.x release refactored the API...
> Router.navigate becomes Cmd.navigate for the Elmish variant...

If someone were working through "The Elmish Book", they would not have installed a Feliz.Router 2.x version. The instructions [here](https://github.com/Zaid-Ajaj/the-elmish-book/blob/8ff6ff2b011be7da31f6ef4e79ae5d0cbfcc8969/chapters/scaling/routing.md?plain=1#L41) say to use `dotnet add package Feliz.Router`. 

I will assemble a PR to reflect Feliz.Router 3.x.
