### ISSUE TITLE
Update on how to make HTTP get post requests in elmish v4

### ISSUE THREAD

**Issue by jchain** [Zaid-Ajaj/the-elmish-book#178]
`elmish` v4 dropped `Cmd.ofSub` and your `Cmd.fromAsync` trick seems no working any more. Can you please provide an example on how to make a HTTP request for `elmish` v4? Thanks!

**Comment by MangelMaxime** [comment]
@jchain If you are using Fetch API, you would work with promise.

And so in that case, you can use `Cmd.ofPromise` module.

You can find the documentation about the new subscription feature [here](https://elmish.github.io/elmish/docs/subscription.html) but I don't think you want to use subscription to make HTTP call.

**Comment by jchain** [comment]
@MangelMaxime Thank you so much for your reply. I have search for the uage of `Cmd.ofPromise` but it was hard to find a working example with `elmish`. The doc at https://elmish.github.io/elmish/ didn't mention it at all. Another link https://medium.com/@MangelMaxime/my-tips-for-working-with-elmish-ab8d193d52fd seems outdated (written by you in 2018)?

**Comment by Zaid-Ajaj** [comment]
@jchain in Elmish v4, `Cmd.ofSub` has been renamed `Cmd.ofEffect` I believe

**Comment by MangelMaxime** [comment]
@jchain 

Usage of the Cmd module is nothing special, you chose inside of `Cmd.OfPromise.XX` if you care about the success, error or both and use the according versus accordingly.

Here is an example, it using Elmish 3 but it didn't change for Elmish 4.

```fs
let private getRandomUser () = promise {
    // We add a delay of 300ms so the button animation is more visible
    do! Promise.sleep 300
    let! response = Fetch.fetch "https://randomuser.me/api/" []
    let! responseText = response.text()
    let resultDecoder = Decode.field "results" (Decode.index 0 User.Decoder)
    return Decode.fromString resultDecoder responseText
}

let update (msg:Msg) (model:Model) =
    match msg with
    | FetchRandomUser ->
        let newModel =
            match model with
            // If we have a current user
            // we keep it while waiting the new user
            | Loaded user ->
                Loading (Some user)
            | _ -> Loading None

        newModel, Cmd.OfPromise.either getRandomUser () FetchResponse FetchError

    // We got a response and decoding succeded
    | FetchResponse (Ok user) ->
        Loaded user, Cmd.none

    // We got a response and decoding failed
    | FetchResponse (Error msg) ->
        JS.console.error msg
        Errored, Cmd.none

    // An error occured, when fetching the new user
    | FetchError error ->
        JS.console.error error.Message
        Errored, Cmd.none
```

**Comment by jchain** [comment]
Thank you so much for the example code!

**Comment by jchain** [comment]
Thank you so much for the example code!
