### ISSUE TITLE
Consider using Guid instead of int for to-do sample

### ISSUE THREAD

**Issue by theimowski** [Zaid-Ajaj/the-elmish-book#32]
I did same for my sample to-do application. As a result you don't need to calculate next number, just pop up `Guid.NewGuid()` and make things simpler

**Comment by OmanF** [comment]
My 2 cents: I'm actually *for* leaving ID as `int` _and_ creating another exercise to convert these to `System.Guid`s.

I did just that as practice and, with VSCode's superb support of F# (thank you Krzysztof and team!) finding all broken types and refactoring them was both a breeze (to find) and a good, low-hanging-yet-still-a-challenge exercise, so I can attest first-hand it's doable even by total n00bs.

That, and, in the spirit of DDD, swapping a todo's `Completed`, shall I say "field", from a `bool` to a well-defined type (I personally went for `type CompletionState = TodoComplete | TodoPending`, but obviously that's just words. The main idea is to use domain types to distinguish two separate states the todo can be in... not that _you_ need _me_ teaching you that).

**Comment by Zaid-Ajaj** [comment]
@OmanF that actually sounds a good idea to make an exercise of it. I will see what I can do what I make some time for book updates :smile:

**Comment by Zaid-Ajaj** [comment]
Added as an exercise by @OmanF, thanks a bunch 🙏
