### ISSUE TITLE
Remove/change section about yields

### ISSUE THREAD

**Issue by Shmew** [Zaid-Ajaj/the-elmish-book#59]
Now that yields are implicit you can remove parts of/clean-up this [page](https://zaid-ajaj.github.io/the-elmish-book/#/chapters/elm/conditional-rendering#conditional-rendering-using-yield).

**Comment by Zaid-Ajaj** [comment]
Good catch! I thought I removed the comment about RFC being in progress. Will do it soon :smile:

**Comment by Zaid-Ajaj** [comment]
Fixed :fire:
