### ISSUE TITLE
Mismatch between code snippets in 'To-Do List Application: Part 2'

### ISSUE THREAD

**Issue by mtnrbq** [Zaid-Ajaj/the-elmish-book#72]
In the section **Modelling the State**, the type is defined as below:
```fsharp {highlight: [3]}
...
type State = {
  NewTodo: string
  TodoList : Todo list
}
```
However in the **Implementing State Updates** section, the field has changed from `NewTodo` to `NewTodoDescription`

```fsharp {highlight: [4]}
let update msg state =
  match msg with
  | SetNewTodo desc ->
      { state with NewTodoDescription = desc }
```

Please advise which is correct, and I can make the updates in the documentation.

**Comment by Zaid-Ajaj** [comment]
Hello @mtnrbq, great catch! The second snippet should be updated to
```fs
let update msg state =
  match msg with
  | SetNewTodo desc ->
      { state with NewTodo = desc }
```
because that is how the [source code](https://github.com/Zaid-Ajaj/elmish-todo-part2) looks like.
