### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by ThisFunctionalTom** [Zaid-Ajaj/the-elmish-book#83]
At the end of the chapter scaling/introducing-url-type there is a reference to a page [Routing With Login](https://zaid-ajaj.github.io/the-elmish-book/#/chapters/scaling/routing-with-login) which is not found. I guess it is still not written?

**Comment by Zaid-Ajaj** [comment]
Hi there @tenigma, thanks a lot for pointing it out, I think it is written by the URL is incorrect. I will check it out
