### ISSUE TITLE
Section: elm>conditional-rendering about yield statement at the end

### ISSUE THREAD

**Issue by Nordes** [Zaid-Ajaj/the-elmish-book#84]
Hi Zaid, thank you for your work. 

In the page https://zaid-ajaj.github.io/the-elmish-book/#/chapters/elm/conditional-rendering you mention that the yield keyword will become implicit. The link point to one of the issue, but it is now been implemented in https://github.com/dotnet/fsharp/pull/6806

> The only downside of this approach is that all other elements need to be yielded as well. Because this pattern is used a lot in Fable/F# projects, there are discussions of making yield implicit in the coming versions of F#, see F# RFC FS-1069 - Implicit yields .

**Comment by Zaid-Ajaj** [comment]
You are totally right, it is old section I wrote before that feature was implemented :smile: I will clarify it in the page. Thanks a lot for pointing it out :pray:

**Comment by Zaid-Ajaj** [comment]
Fixed :fire:
