### ISSUE TITLE
Inconsistent Msg for NewTodo between todo part 1 and 2

### ISSUE THREAD

**Issue by Nordes** [Zaid-Ajaj/the-elmish-book#88]
In the Todo Part 1, we can see `AddTodo` while in the part 2 we see `AddNewTodo`. Probably, it would be better to stay consistent in order for someone to pass from part 1 to part 2. Personally `Add` and `New` seems pretty much similar and `AddTodo` makes more sense.

Also, at the beginning of the part 2, we can see clearly that it is still `AddTodo` in the scenario, but not in the code sample later in the page.

https://zaid-ajaj.github.io/the-elmish-book/#/chapters/elm/todo-app-part1
https://zaid-ajaj.github.io/the-elmish-book/#/chapters/elm/todo-app-part2

**Comment by Zaid-Ajaj** [comment]
Great catch! I have fixes the inconsistency and made part 1 follow what part 2 and 3 are doing (it was easier to modify part 1 because part 2 and 3 are bigger). I also modified the source code of the application. 

Thanks a lot for pointing these out :pray: please keep 'em coming

**Comment by Nordes** [comment]
You're welcome. Nice writing by the way. I saw some other inconsistency, but nothing to worry about (spacing with `:` when defining types. Sometimes you have space and sometimes not 

e.g.:
```
type A = {
  LittleFoo: string
  BigBar : int
}
```

I won't open an issue on this, I sometimes end up doing the same while coding ;).
