### ISSUE TITLE
To-Do (part 2) - Box layout image/svg instead of paint

### ISSUE THREAD

**Issue by Nordes** [Zaid-Ajaj/the-elmish-book#89]
The box layout could look like the following:

![image](https://user-images.githubusercontent.com/446572/77726963-90ecad00-703c-11ea-84ae-1b0098b1d7c9.png)

[To-Do_box_layout.txt](https://github.com/Zaid-Ajaj/the-elmish-book/files/4391775/To-Do_box_layout.txt) (to be renamed with extension .drawio and to be opened on https://draw.io or https://app.diagrams.net).

If you prefer ;) keep, otherwise just close this issue.

url: https://zaid-ajaj.github.io/the-elmish-book/#/chapters/elm/todo-app-part2

**Comment by Zaid-Ajaj** [comment]
Awesome, this is much much better! I added it to the part 2 of the Elmish todo. Thanks a lot :pray:
