### ISSUE TITLE
AsyncOperationStatus or AsyncOperationEvent

### ISSUE THREAD

**Issue by markpattison** [Zaid-Ajaj/the-elmish-book#99]
In the very last line of the [Elmish HackerNews: Exercises](https://zaid-ajaj.github.io/the-elmish-book/#/chapters/commands/elmish-hackernews-exercises) chapter, you hint that `LoadedStoryItem` should be refactored into `int * AsyncOperationStatus<Result<HackernewsItem, string>>`.

Should the [starting code for the exercises](https://github.com/Zaid-Ajaj/elmish-hackernews-part3) define `AsyncOperationStatus` rather than `AsyncOperationEvent` in `Extensions.fs`?  As far as I can tell, they do the same thing.

**Comment by Zaid-Ajaj** [comment]
Hello Mark! Thanks for pointing this out 🙏 Indeed it has to be `AsyncOperationStatus` I though I changed everywhere but it seems I missed that in one place. I will change is ASAP

**Comment by Zaid-Ajaj** [comment]
Fixed the source code of the part 3 to use AsyncOperationStatus instead. Thanks again!
